name: Child Pipeline A

on:
  push:
    branches:
      - 'feature/*'
    paths:
      - 'src/a/**'
      - 'src/index.js'

jobs:
  a:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/hydrogen
      - uses: pnpm/action-setup@v2
        with:
          version: 7.x

      - name: Install Dependencies
        run: pnpm i

      - name: Build
        run: sleep 20 && pnpm prettier:check

      - name: Test
        run: sleep 20 && pnpm test:unit:a

      - name: Deploy
        run: pnpm release:a
